apiVersion: v1
kind: ConfigMap
metadata:
  name: idempotency-config
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: update

---

apiVersion: v1
kind: Secret
metadata:
  name: idempotency-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%s/%s"  (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}
