{
 "title": "Users app",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "db_instance", "label": "DB instance", "query": "query_result(pg_up)" },
   { "name": "db_name", "label": "DB name", "query": "label_values(datname)" }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri)(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\nsum by (le, uri)\n(rate(http_server_requests_seconds_bucket[1m]))\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\nsum by (le, uri)\n(rate(http_server_requests_seconds_bucket[1m]))\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\nsum by (le, uri)\n(rate(http_server_requests_seconds_bucket[1m]))\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P100 Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0,\nsum by (le, uri)\n(rate(http_server_requests_seconds_bucket[1m]))\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Ingress rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Ingress percentile response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{host!=\"_\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{host!=\"_\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{host!=\"_\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1.0,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{host!=\"_\"}[1m])))",
     "legendFormat": "1.0"
    }
   ]
  },
  {
   "title": "Ingress error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU (App)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", container=\"users-chart\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container=\"users-chart\"}[5m])) by (container)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory usage (App)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"users-chart\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"users-chart\"}) by (container)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DB Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"$db_instance\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "DB Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"$db_instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$db_instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  }
 ]
}