apiVersion: v2
name: users-chart
description: A Helm chart for users service.

type: application

version: 1.3.5
appVersion: 1.1.0

dependencies:
  - name: postgresql
    version: 10.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - users-database
