apiVersion: v2
name: idempotency-chart
description: A Helm chart for users service.

type: application

version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    version: 10.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - idempotency-database
