replicaCount: 2

image:
  repository: amogilevskiy/otus-k8s-idempotency

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true

postgresql:
  enabled: true
  postgresqlUsername: user
  postgresqlPassword: pewpewpew
  postgresqlDatabase: otus
  service:
    port: "5432"